- name: Configurer la VM Kubernetes
  hosts: kubernetes
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer les prérequis (Docker, Git, curl)
      apt:
        name:
          - docker.io
          - git
          - curl
        state: present

    - name: Démarrer Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Installer kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Installer Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    - name: Ajouter l'utilisateur ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes
